
openssl genpkey -algorithm RSA -out private.pem -pkeyopt rsa_keygen_bits:2048
mkdir -p src/main/resources/META-INF
openssl rsa -in private.pem -pubout -out src/main/resources/META-INF/public.pem

mvn exec:java -Dexec.mainClass=org.wildfly.examples.TokenUtil -Dexec.classpathScope=test -Dexec.args="testUser 2017-09-15 Echoer"

curl -H "Authorization: Bearer eyJraWQiOiJUZXN0IEtleSIsInR5cCI6Imp3dCIsImFsZyI6IlJTMjU2In0.eyJzdWIiOiJ0ZXN0VXNlciIsInVwbiI6InRlc3RVc2VyIiwiaXNzIjoicXVpY2tzdGFydC1qd3QtaXNzdWVyIiwiYXVkIjoiand0LWF1ZGllbmNlIiwiZ3JvdXBzIjpbIkVjaG9lciJdLCJiaXJ0aGRhdGUiOiIyMDE3LTA5LTE1IiwianRpIjoiNGQwZjlhMzgtNTc2Yi00NTY4LTg3ODEtMWU1ODkxZTgyYjAzIiwiaWF0IjoxNzI3MTk1NDgzLCJleHAiOjE3MjcyMDk4ODN9.IgjycuixlBvfiqv0p5l7zW2bQRSpHMfP_Z1SJK9ml5UuRwcv_QbY8ZZNeTRk9HuukPHbgpQkkHvpDYfdma2urwPfiS8RPR7rxvoCHu41BwrZ_MJStTk0NNGO35FEC9zwoY8JsryDSqqQkdkpQlDWrHY6uaZzHR5SpQPdmoUteoP7RCQsjyWIdjI0tOrv_JV0vPErq1tGvhUNjM_DMpYRew0yFtpD7cSQUT5yJfN6LvfOuBK7YE2E1O0UWCTWN5quzHJIovWMWoXhsHGU32VgOdxvkFWYyFnRA8BHLZ0slbfUM2nY1gj4HOBhJ0SFl3yAMZVnj5IqQle9orqz7TpXZA" http://localhost:8080/hello/pippo

= simple-microservice

The `simple-microservice` project is a simple Jakarta EE application with a HTTP endpoint that is running in
https://wildfly.org[WildFly].

The `src/main` folder contains a simple 'Hello world' style Jakarta EE application using JAX-RS.

== Building the application

To build the application, you use Maven:

[source,shell]
----
mvn clean package
----

Maven will compile the application, provision a WildFly server
The WildFly server is created in `target/server` with the application deployed in it.

== Running the application

To run the application, run the commands:

[source,shell]
----
cd target/server
./bin/standalone.sh
----

Once WildFly is running, the application can be accessed at http://localhost:8080/

== Testing the application

To run integration tests to verify the application, you use Maven:

[source,shell]
----
mvn clean package verify
----

Tests in `src/test` are run against the server in `target/server`.

== Build Docker image

[source,shell]
----
podman build -t my-jaxrs-app:latest .
----

== Run Docker image

[source,shell]
----
podman run --rm -p 8080:8080 -p 9990:9990 \
  --name=my-jaxrs-app \
  my-jaxrs-app
----

== Deploy to Kubernetes

[source,shell]
----
podman tag my-jaxrs-app quay.io/tborgato/my-jaxrs-app
podman push quay.io/tborgato/my-jaxrs-app
----

NOTE: in the above commands, replace `tborgato` with your personal account

[source,shell]
----
kubectl apply -f kubernetes/deployment-my-jaxrs-app.yaml
kubectl expose deployment.apps/my-jaxrs-app-deployment --type=NodePort --port=8080
----

NOTE: in the above files, replace `tborgato` with your personal account

== Resources

* https://wildfly.org[WildFly]
* https://docs.wildfly.org[WildFly Documentation]
